apiVersion: 1

datasources:
- name: InfluxDB
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb-service:8086
  database: grafana
  editable: false
  basicAuthUser: wmadison
  basicAuthPassword: wmadison