apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-app
  annotations:
    metallb.universe.tf/allow-shared-ip: ip-loadbalancer
spec:
  selector:
    app: grafana-app
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: grafana-port
      name: grafana-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: wmadison
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: wmadison
        image: grafana_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana-port
