apiVersion: v1
kind: Service
metadata:
  name: pma-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ip-loadbalancer
spec:
  selector:
    app: pma-app
  type: LoadBalancer
  ports:
    - port: 5000
      name: pma-port
      protocol: TCP
      targetPort: pma-port
     
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma-app
  template:
    metadata:
      name: pma-pod
      labels:
        app: pma-app
    spec:
      containers:
      - name: pma
        image: pma_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: pma-port